name: Build and Push to Docker Hub
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - run: pnpm run ci
      - run: pnpm run build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rankland-fe:latest
  build-and-push-for-cn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - run: pnpm run ci:server
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Image for CN Site
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          file: ./Dockerfile-CN
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rankland-fe:cn
  build-and-push-for-cnn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - run: pnpm run ci
      - run: SITE_ALIAS=cnn pnpm run build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Image for CN Next Site
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          file: ./Dockerfile-CN-Next
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rankland-fe:cnn
